// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRequirements(arg1, arg2) {
  return window['go']['main']['App']['CheckRequirements'](arg1, arg2);
}

export function GetGameRequirements(arg1) {
  return window['go']['main']['App']['GetGameRequirements'](arg1);
}

export function GetHardwareInfo() {
  return window['go']['main']['App']['GetHardwareInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchGame(arg1) {
  return window['go']['main']['App']['SearchGame'](arg1);
}
