// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';

export function CheckRequirements(arg1:structs.SystemSpecs,arg2:structs.GameData):Promise<structs.RequirementsResult>;

export function GetGameRequirements(arg1:number):Promise<structs.GameData>;

export function GetHardwareInfo():Promise<structs.SystemSpecs>;

export function Greet(arg1:string):Promise<string>;

export function SearchGame(arg1:string):Promise<Array<structs.SteamApp>>;
